plugins:
  - jekyll-remote-theme

theme: minima
# remote_theme: cotes2020/jekyll-theme-chirpy
# remote_theme: artemsheludko/flexible-jekyll@latest
title: devops.express 
author: Aric H.
description: Bite-size musings from my DevOps endeavours
